### ISSUE TITLE
Hidden commands throw IndexError when requested by help command.

### ISSUE THREAD

**Issue by SkylaDev** [stshrewsburyDev/discord-better-help#6]
Enabling the `hidden` attribute on commands will hide them from help menu's as expected but will also cause an index error if mentioned.

Example:
```python
@bot.command(name="test", hidden=True)
async def test(ctx):
    await ctx.reply("Haha you found this command!")
```
When running `!help test` nothing will send and instead this error will appear in console:
```python
Ignoring exception in command help:
Traceback (most recent call last):
  File "\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "\venv\lib\site-packages\discord\ext\commands\help.py", line 880, in command_callback
    return await self.send_group_help(cmd)
  File "\venv\lib\site-packages\better_help\help.py", line 203, in send_group_help
    await self.send_pages()
  File "\venv\lib\site-packages\better_help\help.py", line 88, in send_pages
    message: discord.Message = await destination.send(embed=pages[0])
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\venv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "\venv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "\venv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range
```
Not fully sure how this error is being caused but I will look into it at the first chance I get.

**Comment by SkylaDev** [comment]
Cause of the bug has been found and sorted with, expect this bug fix to be released in 1.2 later today/this weekend.
